version: '3.8'  

services:  
  frontend:  
      build: ./frontend  
          ports: ["3000:3000"]  

            backend:  
                build: ./backend  
                    ports: ["8000:8000"]  
                        depends_on:  
                              - postgres  

                                postgres:  
                                    image: postgres:14  
                                        environment:  
                                              POSTGRES_PASSWORD: devhelpchatoncetoldastory@&6$3&3